### ISSUE TITLE
Brewformer ver 1.0.0 checklist

### ISSUE THREAD

**Issue by ZaBAOW** [ZaBAOW/brewformer#9]
Thinkful release issues:
- [x]  create nav bar for help, search, and about pages.
- [x]  create an about and a help page for the user.
- [x]  filter beers so that they display under respective brewery.
- [x]  find a way to display beer data prior to user click.
        ```description of beer in a tooltip that displays while hovering beer```
- [x]  figure out where the site should send the user if a beer is clicked.
        ```should it be a specific site or just a google search?```
- [x]  provide clarity for the user with hover effects (materialize.js).
        ```want both the brewery container to have shadow effect.```
        ```want beer items to have font color changing effects.```
- [x]  make sure the footer has the proper elements.
         ```read through brewerydb, materialize.js for api request requirements.``` 
- [x]  make sure site is aria compatible.

After Thinkful release issues:
- [x]  integrate app icon into site.
- [x]  improve styling choices for the site.

**Comment by ZaBAOW** [comment]
Displaying beer data prior to click:
- [] need to solve issue with quotation marks
- [] need to recognize when description is undefined.
